const contstants = {
  SELECT_TEAM: 'SELECT_TEAM',
  SET_ROUNDS: 'SET_ROUNDS',
  SET_BIG_BOARD: 'SET_BIG_BOARD',
  FILTER_PLAYERS: 'FILTER_PLAYERS',
  ADD_PLAYER: 'ADD_PLAYER',
  CANCEL_ADDING_PLAYER: 'CANCEL_ADDING_PLAYER',
}

export default constants;
